target 'BCBalancedMultilineLabel', :exclusive => true do
  pod "BCBalancedMultilineLabel", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BCBalancedMultilineLabel", :path => "../"

  pod 'FBSnapshotTestCase'
end
