language: objective-c
before_install: gem install cocoapods && cd Example && pod install && cd -
script:
- xctool test -workspace Example/BCBalancedMultilineLabel.xcworkspace -scheme BCBalancedMultilineLabel-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 5'
