language: objective-c
# before_install: cd Example && pod install && cd -
script:
- xctool test -workspace Example/BCBalancedMultilineLabel.xcworkspace -scheme BCBalancedMultilineLabel -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone Retina (4-inch)'
